# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/tb-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter TB8703 TB8704 TBX704 TB8504 TBX304,$(TARGET_DEVICE)),)

endif
